### ISSUE TITLE
Details of downloading image data for VisualCSE

### ISSUE THREAD

**Issue by voidism** [yiren-jian/NonLing-CSE#1]
Hi!

Thanks so much for releasing the code for your NeurIPS paper! I am wondering where can I download the ImageNet-1K data as shown in the following in your README?
```
...
/datasets/sampled-Imagenet/n01871265/n01871265_7110.JPEG
/datasets/sampled-Imagenet/n01871265/n01871265_3107.JPEG
/datasets/sampled-Imagenet/n01871265/n01871265_8069.JPEG
/datasets/sampled-Imagenet/n01871265/n01871265_4796.JPEG
/datasets/sampled-Imagenet/n01871265/n01871265_6902.JPEG
/datasets/sampled-Imagenet/n01871265/n01871265_389.JPEG
...
```

I checked https://image-net.org/download-images.php and registered and got approved, but there are so many download links on the website. It's not obvious which one did you use. Can you provide more details about how to download it? I am an NLP folk so I don't not much about the image datasets. Thanks!

**Comment by yiren-jian** [comment]
ILSVRC2012_img_train.tar & ILSVRC2012_img_val.tar should be what you need. You should also find this [preprocessing script](https://github.com/pytorch/examples/blob/main/imagenet/extract_ILSVRC.sh) helpful.

**Comment by voidism** [comment]
@yiren-jian Thanks a lot! I will try it. Also, congrats on the NeurIPS paper!
