### ISSUE TITLE
Planning to release AudioCSE?

### ISSUE THREAD

**Issue by voidism** [yiren-jian/NonLing-CSE#2]
Hi @yiren-jian

Thanks for your help with VisualCSE in #1 . Now I can run the experiment for VisualCSE successfully.
I was wondering if you are planning to release AudioCSE anytime soon? I am currently working on text-audio pretraining so it would be very helpful if I could use the AudioCSE code. Thanks!

**Comment by yiren-jian** [comment]
OK. I will work on it and hopefully I can make it this weekend.

**Comment by yiren-jian** [comment]
Hi @voidism ,

I have uploaded the code for AudioCSE. However the code is a bit messy, 

> The code is directly adapted from VisualCSE. We apologize for the extremely messy code in this repo. You will find that we use image and audio interchangeably in our src/models.py, src/trainer and args in train.py. Please note that they all refer to audio in this repo.

Besides, I include the scripts we used for searching hyper-parameters.  Hope it can help.

**Comment by voidism** [comment]
Thanks for your fast release! It can definitely benefit my research. Thanks a lot for your help.
